apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-app
  namespace: project-10-env
  labels:
    app: gitlab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab-app
  template:
    metadata:
      labels:
        app: gitlab-app
    spec:
      containers:
      - name: gitlab-app
        image: nginx:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-app-svc
  namespace: project-10-env
spec:
  type: NodePort
  selector:
    app: gitlab-app
  ports:
    - port: 8080
      targetPort: 8080
