apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://gitlab.com/talal41419/gitops-app.git
    targetRevision: HEAD
    path: apps/task-manager/k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
